### ISSUE TITLE
context.yaml has no affect on parent_env* functions

### ISSUE THREAD

**Issue by sadministrator** [mel-project/melodeon#29]
Even if you specify parent fields in a context file, the information is ignored for parent functions.

context.yaml
```
# parent_tx_hash() should be 0xafaac4c8835a322fab6dcf0d95b36e1726b01153594692dfaf4eb769fd309236
parent_value: 261975609902968496378757644630085902329
parent_denom: ERG
additional_data: 4fdd02c537aa4cab34b4a89740ef516938e5dfec
```

Output:
```
$ melorun -i -s context.yaml
melorun> env_parent_tx_hash()
- : %[32]
x"0000000000000000000000000000000000000000000000000000000000000000"

melorun> env_parent_denom()
- : %[]
"d"
```

**Comment by nullchinchilla** [comment]
so the `env_parent_denom()` seems to be correct ("d" is for ERG, weirdly enough; it's because it used to be "DOSC"). `env_parent_value()` should also be correct

Right now I think the issue is that I'm not generating the `env_parent_tx_hash()` for the fake environment correctly, but I'm not sure there *is* a way of doing it correctly. The `parent_*` parameters in `context.yaml` specify facts about the *coin* locked by this covenant, but that is fundamentally not enough to reconstruct every field of the *transaction that created the coin* and compute the hash.

Do you think I should just add a `parent_tx_hash` field in `context.yaml` that "fakes" the hash?

**Comment by sadministrator** [comment]
Ah, I didn't check `env_parent_value()` and got confused by the `"d"`  haha.

And yeah, I think that would be a good addition to the context file specification.

Maybe later on we can make it dependent on the coin value, denom, and data if they are specified but it doesn't seem like a huge priority at the moment.

**Comment by nullchinchilla** [comment]
Yeah, I'll just add it then. Originally I didn't consider that there might be covenants that cared about the particular hash (since it's entirely unpredictable), but I suppose cross-chain stuff is a big case where the literal hash is often used.

**Comment by nullchinchilla** [comment]
Melorun 0.7.9 fixes this.
